mtchat:
  jwt:
    secret-key: mtandmm
  mysql:
    host: 110.41.49.248
    port: 33106
    username: root
    password: .z192m128t3015.
    database: mtchat
  redis:
    host: 110.41.49.248
    port: 61379
    password: z192m128
    database: 1
  wx:
    app-id: wxee25fb4bc0926c6b
    aes-key: 1
    secret: df77b688b3a8785911558b8fe79ef32b
    token: mtlaa
    callback: http://110.41.49.248:8080

rocketmq:
  name-server: 110.41.49.248:9876
  access-key: mychatMT
  secret-key: z192m128

oss-dev:
  enabled: true
  type: minio
  endpoint: http://110.41.49.248:19000
  access-key: w3wbN4phN8QPVS7xIwVz
  secret-key: DMu7a20IvBLPxEeqEsLOprq3F3ACNvQlv2RnWTwL
  bucketName: mtchat